// Ionic/Ionic5React17/protected/src/components/Character.tsx
import { Component } from 'react';
import { getPeopleData } from "../util/provider";

type MyState = {
  loader: Boolean,
  result: Array<[]>
};

class Character extends Component<{}, MyState> {
  constructor(props: any) {
    super(props);

    this.state = {
      loader: true,
      result: []
    };
  }

  /**
   * on component mount fetch list of planets from SWAPI
   */
  componentDidMount = () => {
    this.getResult();
  }
  
  /**
   * this method is used to fetch the list of planets
   */
  getResult = () => {
    this.setState({ loader: true });

    getPeopleData()
      .then((resp) => this.apiSuccessCallback(resp))
      .catch(() => this.apiFailureCallback());
  }

  /**
   * this method is planets api success callback, set the data into state
   */
  apiSuccessCallback = (resp: any) => {
    let data = resp.data.results;

    this.setState({
      result: data,
      loader: false,
    });
  }

  /**
   * this method is planets api failure callback, shows error
   */
  apiFailureCallback = () => {
    this.setState({ loader: false });
    alert("Something went wrong!!");
  }

  render() {
    let loader = null;
    if (this.state.loader) {
      loader = <div>
        <div className="loader"></div>
        <div id="overlay"></div>
      </div>;
    } else {
      loader = null;
    }

    return (
      <div className="row">
        <div className="col-md-12">
          {this.state.result.map((item: any, i: any) => {
              return(
                <div className="response" key={i}>
                  <p className="card-title">{item.name}</p>
                  <table className="table table-borderless table-responsive">
                    <tbody>
                      <tr className="card-heading-1">
                        <td>Height</td>
                        <td>Mass</td>
                        <td>Hair color</td>
                        <td>Skin color</td>
                        <td>Birth year</td>
                        <td>Gender</td>
                      </tr>
                      <tr className="card-heading-2">
                        <td>{item.height}</td>
                        <td>{item.mass}</td>
                        <td>{item.hair_color}</td>
                        <td>{item.skin_color}</td>
                        <td>{item.birth_year}</td>
                        <td>{item.gender}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              );
          })}
        </div>
        {loader}
      </div>
    );
  }
};

export default Character;

// Ionic/Ionic8Vue3/protected/src/views/Character.vue
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button color="primary"></ion-menu-button>
        </ion-buttons>
        <ion-title>Characters</ion-title>
      </ion-toolbar>
    </ion-header>
    
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Characters</ion-title>
        </ion-toolbar>
      </ion-header>
      <div id="container">
        <div className="row">
          <div className="col-md-12">
            <div className="response" v-for="item in data" :key="item.name">
              <p className="card-title">{{item.name}}</p>
              <table className="table table-borderless table-responsive">
                <tbody>
                  <tr className="card-heading-1">
                    <td>Height</td>
                    <td>Mass</td>
                    <td>Hair color</td>
                    <td>Skin color</td>
                    <td>Birth year</td>
                    <td>Gender</td>
                  </tr>
                  <tr className="card-heading-2">
                    <td>{{item.height}}</td>
                    <td>{{item.mass}}</td>
                    <td>{{item.hair_color}}</td>
                    <td>{{item.skin_color}}</td>
                    <td>{{item.birth_year}}</td>
                    <td>{{item.gender}}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div v-if="loading">
          <div className="loader"></div>
          <div id="overlay"></div>
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script>
  import { IonButtons, IonContent, IonHeader, IonMenuButton, IonPage, IonTitle, IonToolbar } from '@ionic/vue';
  import { getPeopleData } from "../util/provider";

  export default {
    name: 'Folder',
    components: {
      IonButtons,
      IonContent,
      IonHeader,
      IonMenuButton,
      IonPage,
      IonTitle,
      IonToolbar
    },
    data: () => {
      return {
        data: [],
        loading: false
      }
    },
    methods: {
      /**
      * this method is used to fetch list of planets from SWAPI, and set data
      */
      fetchData() {
        this.loading = true;
        getPeopleData()
        .then((resp) => {
          this.loading = false;
          this.data = resp.data.results;
        }).catch(() => {
          alert('Something went wrong');
          this.loading = false;
        });
      }
    },
    /**
    * fetch list of planets from SWAPI on mount
    */
    mounted() {
      this.fetchData();
    },
  }
</script>
