// Ionic/Ionic5Vue3/original/src/views/Film.vue
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button color="primary"></ion-menu-button>
        </ion-buttons>
        <ion-title>Movies & Shows</ion-title>
      </ion-toolbar>
    </ion-header>
    
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Movies & Shows</ion-title>
        </ion-toolbar>
      </ion-header>
      <div id="container">
        <div className="row">
          <div className="col-md-12">
            <div className="response" v-for="item in data" :key="item.name">
              <p className="card-title">{{item.name}}</p>
              <table className="table table-borderless table-responsive">
                <tbody>
                  <tr className="card-heading-1">
                    <td>Title</td>
                    <td>Director</td>
                    <td>Producer</td>
                    <td>Release date</td>
                  </tr>
                  <tr className="card-heading-2">
                    <td>{{item.title}}</td>
                    <td>{{item.director}}</td>
                    <td>{{item.producer}}</td>
                    <td>{{item.release_date}}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div v-if="loading">
          <div className="loader"></div>
          <div id="overlay"></div>
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script>
  import { IonButtons, IonContent, IonHeader, IonMenuButton, IonPage, IonTitle, IonToolbar } from '@ionic/vue';
  import { getFilmData } from "../util/provider";

  export default {
    name: 'Folder',
    components: {
      IonButtons,
      IonContent,
      IonHeader,
      IonMenuButton,
      IonPage,
      IonTitle,
      IonToolbar
    },
    data: () => {
      return {
        data: [],
        loading: false
      }
    },
    methods: {
      /**
      * this method is used to fetch list of planets from SWAPI, and set data
      */
      fetchData() {
        this.loading = true;
        getFilmData()
        .then((resp) => {
          this.loading = false;
          this.data = resp.data.results;
        }).catch(() => {
          alert('Something went wrong');
          this.loading = false;
        });
      }
    },
    /**
    * fetch list of planets from SWAPI on mount
    */
    mounted() {
      this.fetchData();
    },
  }
</script>

// Ionic/Ionic5React17/protected/src/components/Film.tsx
import { Component } from 'react';
import { getFilmData } from "../util/provider";

type MyState = {
  loader: Boolean,
  result: Array<[]>
};

class Film extends Component<{}, MyState> {
  constructor(props: any) {
    super(props);

    this.state = {
      loader: true,
      result: []
    };
  }

  /**
   * on component mount fetch list of planets from SWAPI
   */
  componentDidMount = () => {
    this.getResult();
  }
  
  /**
   * this method is used to fetch the list of planets
   */
  getResult = () => {
    this.setState({ loader: true });

    getFilmData()
      .then((resp) => this.apiSuccessCallback(resp))
      .catch(() => this.apiFailureCallback());
  }

  /**
   * this method is planets api success callback, set the data into state
   */
  apiSuccessCallback = (resp: any) => {
    let data = resp.data.results;

    this.setState({
      result: data,
      loader: false,
    });
  }

  /**
   * this method is planets api failure callback, shows error
   */
  apiFailureCallback = () => {
    this.setState({ loader: false });
    alert("Something went wrong!!");
  }

  render() {
    let loader = null;
    if (this.state.loader) {
      loader = <div>
        <div className="loader"></div>
        <div id="overlay"></div>
      </div>;
    } else {
      loader = null;
    }

    return (
      <div className="row">
        <div className="col-md-12">
          {this.state.result.map((item: any, i: any) => {
              return(
                <div className="response" key={i}>
                  <p className="card-title">{item.name}</p>
                  <table className="table table-borderless table-responsive">
                    <tbody>
                      <tr className="card-heading-1">
                        <td>Title</td>
                        <td>Director</td>
                        <td>Producer</td>
                        <td>Release date</td>
                      </tr>
                      <tr className="card-heading-2">
                        <td>{item.title}</td>
                        <td>{item.director}</td>
                        <td>{item.producer}</td>
                        <td>{item.release_date}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              );
          })}
        </div>
        {loader}
      </div>
    );
  }
};

export default Film;
